---
title: "Reproducibilidad en R: Compartiendo entornos interactivos con Binder"
output: html_document
---

¿Basta con dejar disponible el código y las bases de datos de tu trabajo para que otra persona (o tu yo del futuro) pueda volver a correrlo sin problemas?

Las herramientas y prácticas que mejoran la reproducibilidad computacional no siempre se abordan en los cursos de programación. Algunas forman parte de "eso que se olvidaron de enseñarte de R": control de versiones, sistemas de administración de dependencias, programación literaria, entre otras.

En este meetup de R-Ladies Buenos Aires, Florencia D'Andrea nos brinda un panorama de por qué es interesante abordar el tema de la reproducibilidad, publiques o no artículos científicos. Además presentamos la hackatón de reproducibilidad científica (reproHack) que tuvo lugar como parte de la edición virtual de LatinR 2020.

Podés revivir el encuentro acá:

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/-7G7tlmB2Ts" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
