---
title: "Introducción al ABC para enseñar on-line"
output: html_document
---

R-Ladies Santa Rosa y R-Ladies General Pico abrieron sus puertas virtuales al taller Introducción al ABC para enseñar on-line de [MetaDocencia](https://www.metadocencia.org/) durante LatinR 2020.

**Sobre el taller**

Vamos a introducir buenas prácticas básicas para manejo del aula presencial online. Cada detalle del taller, empezando por el formulario de pre-inscripción hasta el pedido de devolución finalizado el taller, pasando por la ejecución del mismo, son una demostración de estrategias que pueden ser adoptadas o adaptadas a cualquier tarea docente que sucede interactuando en simultáneo con estudiantes. Durante el taller tendremos una demostración de cómo contactar y preparar estudiantes para sumarse a la clase sincrónica, cómo manejar un aula virtual de 20 personas usando Zoom, veremos ejemplos para crear un ambiente positivo y tendremos una introducción a conceptos pedagógicos de diseño de clases con foco en la audiencia, esquematización de contenidos con mapas conceptuales, evaluación formativa con poder diagnóstico, participación en un documento colaborativo para tomar notas y resolver evaluaciones formativas y otras herramientas pedagógicas basadas en evidencia y fáciles de implementar.


Una versión de este taller (grabada previo a LatinR):

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/ojh4KgV0p3g" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
