---
title: "useR! 2020 online tutorial: Predictive modeling with text using tidy data principles"
output: html_document
---

Los capítulos de R-Ladies de Argentina nos unimos para recibir a Emil Hvitfeldt y Julia Silge se y su tutorial en useR2020 "Predictive modeling with text using tidy data principles (Modelado predictivo con texto utilizando principios de datos tidy)".

**Sobre el tutorial**

* ¿Alguna vez encontraste datos de texto y sospechaste que había información útil en esos datos?, ¿Te sentiste con frustración al intentar ver cómo encontrar esa información?
* ¿Estás familiarizade con los conceptos básicos del modelado predictivo y estás liste para aprender cómo se pueden usar los datos de texto no estructurados para la predicción dentro de los ecosistemas tidyverse y tidymodels?
*¿Necesitas un marco flexible para manejar datos de texto que te permitan construir modelos predictivos supervisados?

Los datos de texto son cada vez más importantes en muchos dominios y los principios de tidymodels se pueden aplicar a las tareas de procesamiento del lenguaje natural. Esta presentación está diseñada para proporcionar orientación práctica y conocimiento directamente aplicable para científiques de datos y analistas que desean integrar texto en sus proyectos de modelado.

En este tutorial de 90 minutos aprende a preprocesar datos de texto para modelar, entrenar modelos y evaluar el rendimiento del modelo. Podés encontrar los materiales [acá](https://github.com/EmilHvitfeldt/useR2020-text-modeling-tutorial) y revivir el tutorial acá:

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/Sz8RB_fPYOk" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

